name: Documentation

on:
    workflow_run:
        workflows:
        - Rust
        types:
        - completed

jobs:
    build:
        permissions:
          contents: write
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install lld and clang
          run: sudo apt-get install lld clang -y --no-install-recommends
        - uses: actions/cache@v3
          with:
            path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                target/
            key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}
        - name: Build Documentation
          run: cargo doc --no-deps --document-private-items
        - name: Doc Index Page Redirection
          run: echo '<meta http-equiv="refresh" content="1; url=RDOGH/index.html">' > target/doc/index.html
        - name: Deploy Documentation
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: target/doc
            force_orphan: true
